### ISSUE TITLE
TODO for publishing mix it content

### ISSUE THREAD

**Issue by dduportal** [jmMeessen/devbox#38]
Todo liste for mix it content :
- [x] Create tag "Demo1" with the running first demo : https://github.com/jmMeessen/devbox/releases/tag/Demo1
- [x] Merge "demo2" branch to "development" in order to complete slides content : https://github.com/jmMeessen/devbox/pull/37
- [x] Update documentation on "development" to refers to `make gui` command by default for X2Go, and use current instructions as "fallback" ones.
- [x] Check content of presentation
- [x] Validate demo2 (JMM)
- [x] Write instructions for demo2
- [x] Write "tagged" github links inside slides
- [x] Export presentation to PDF (committing the PDF file in the repository)
- [x] Merge to master and Tag "demo2" and "slides"
- [x] Export presentation to Slideshare (DDU : I have an account)

**Comment by jmMeessen** [comment]
Je crois que tout a été fait.
